
server:
  port: 8686
  servlet:
    context-path: /exercise


spring:
  cache:
    # 使用 caffeine 作为spring cache
    type: caffeine


  #国际化配置 ---> i18n
  messages:
    basename: i18n/user/messages
    encoding: UTF-8


